version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      .env
    volumes:
       - ./vw-data:/data
    ports:
      - 8000:80
